package com.wafflestudio.seminar.global.common.exception

enum class ErrorType (
    val code: Int
) {
    INVALID_REQUEST(0),
    INVALID_ONLINE_REQUEST(1),
    INVALID_TIME_REQUEST(2),
    INVALID_CAPACITY_REQUEST(3),
    ALREADY_CHARGE(4),
    ALREADY_ENTER(5),
    ALREADY_FULL(6),

    NOT_ALLOWED(3000),
    NOT_INSTRUCTOR(3001),
    NOT_CHARGE(3002),
    NOT_ROLE_SUITABLE(3003),
    NOT_ACCEPTED(3004),

    DATA_NOT_FOUND(4000),
    SURVEY_RESPONSE_NOT_FOUND(4001),
    OS_NOT_FOUND(4002),
    USER_NOT_FOUND(4003),
    SEMINAR_NOT_FOUND(4004),

    CONFLICT(9000),
    USER_ALREADY_EXISTS(9001),
    ALREADY_PARTICIPANT(9002),

    SERVER_ERROR(10000)
}
